#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
python -m compileall -q backend
pytest
frame-trace demo >/tmp/frame-trace-demo.txt
frame-trace evaluate >/tmp/frame-trace-eval.txt
if [ -d frontend/node_modules ]; then
  (cd frontend && npm run typecheck && npm test && npm run build)
fi
if grep -RniE --exclude-dir=.git --exclude-dir=.venv --exclude-dir=node_modules --exclude=verify_release.sh \
  'ChatGPT|Codex|Claude notes|system prompt|sniper prompt|generated by AI|as an AI|/Users/' .; then
  echo "release debris scan failed" >&2
  exit 3
fi
printf 'FRAME TRACE RELEASE CHECK PASSED\n'
